### ISSUE TITLE
sklearn 0.24 issue - AttributeError: 'DecisionTreeClassifier' object has no attribute 'cv'

### ISSUE THREAD

**Issue by mattharrison** [DistrictDataLabs/yellowbrick#1139]
I hacked around #1137 (see code below) to get YellowBrick to load w/ 0.24. However, when I tried to create a ValidationCurve it failed.

**To Reproduce**

```python
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import datasets, metrics, model_selection, tree
import sklearn.utils
sklearn.utils.safe_indexing = sklearn.utils._safe_indexing  # v0.24 / YB bug 1137
from yellowbrick.model_selection import ValidationCurve

url ='https://github.com/mattharrison/datasets/blob/master/data/titanic3.xls?raw=true'
titanic = pd.read_excel(url)

X_titan = (pd.get_dummies(
    titanic
    [['age', 'sibsp', 'parch', 'fare', 'sex']]
    , drop_first=True)
           .fillna(0)
          )
           
y_titan = titanic.survived

ValidationCurve(tree.DecisionTreeClassifier(criterion='entropy', max_depth=20), 
                param_name='max_depth', param_range=range(1,20), cv=10)
```

**Dataset**
In sample above

**Expected behavior**
Expect a validation curve

**Traceback**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-327-6ad0c32cc286> in <module>
     20 y_titan = titanic.survived
     21 
---> 22 ValidationCurve(tree.DecisionTreeClassifier(criterion='entropy', max_depth=20), 
     23                 param_name='max_depth', param_range=range(1,20), cv=10)

~/envs/menv/lib/python3.8/site-packages/yellowbrick/model_selection/validation_curve.py in __init__(self, model, param_name, param_range, ax, logx, groups, cv, scoring, n_jobs, pre_dispatch, **kwargs)
    179 
    180         # Set the visual and validation curve parameters on the estimator
--> 181         self.set_params(
    182             param_name=param_name,
    183             param_range=param_range,

~/envs/menv/lib/python3.8/site-packages/sklearn/base.py in set_params(self, **params)
    222             # Simple optimization to gain speed (inspect is slow)
    223             return self
--> 224         valid_params = self.get_params(deep=True)
    225 
    226         nested_params = defaultdict(dict)  # grouped by prefix

~/envs/menv/lib/python3.8/site-packages/sklearn/base.py in get_params(self, deep)
    193         out = dict()
    194         for key in self._get_param_names():
--> 195             value = getattr(self, key)
    196             if deep and hasattr(value, 'get_params'):
    197                 deep_items = value.get_params().items()

~/envs/menv/lib/python3.8/site-packages/yellowbrick/utils/wrapper.py in __getattr__(self, attr)
     40     def __getattr__(self, attr):
     41         # proxy to the wrapped object
---> 42         return getattr(self._wrapped, attr)

AttributeError: 'DecisionTreeClassifier' object has no attribute 'cv'
```

**Desktop (please complete the following information):**
 - OS: Linux (WSL2)
 - Python Version 3.8
 - Yellowbrick Version 1.2

**Comment by bbengfort** [comment]
@mattharrison thank you for bringing this to our attention; we're currently dealing with a bevy of issues related to sklearn v0.24 and this appears to be another one. I verified that this code does indeed work with scikit-learn==0.23.2 - so as a potential work around you may have to downgrade the scikit-learn version to use yellowbrick, which is what we're currently doing in our tests. 

I did an analysis of the bug in preparation for our tackling the larger issue in a PR:

In sklearn 0.23.2 the following future warning is raised:

```
venv/lib/python3.7/site-packages/sklearn/base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
```

So it's pretty clear that's what's going wrong here: we were expecting that because `Visualizer` is an `Estimator` that the `set_params` call in [model_selection/validation_curve.py#L181](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/model_selection/validation_curve.py#L181) would correctly introspect the visualizer signature and set the parameters on it rather than the wrapped estimator. So either the params API in sklearn changed or we were never right about this and were just adding extra attributes to the underlying estimator the whole time! 

For `ValidationCurve` the fix is pretty simple, change:

```python
        # Set the visual and validation curve parameters on the estimator
        self.set_params(
            param_name=param_name,
            param_range=param_range,
            logx=logx,
            groups=groups,
            cv=cv,
            scoring=scoring,
            n_jobs=n_jobs,
            pre_dispatch=pre_dispatch,
        )
```

to 

```python
        # Set the visual and validation curve parameters on the visualizer
        self.param_name=param_name
        self.param_range=param_range
        self.logx=logx
        self.groups=groups
        self.cv=cv
        self.scoring=scoring
        self.n_jobs=n_jobs
        self.pre_dispatch=pre_dispatch
```

However, it appears that we are making a `Visualizer.set_params` call in the following places:

- test_importances.py L373 and L377
- rfecv.py L148 (not L193 - this is on the rfe estimator)
- ~alphas.py L132~ (this is on the estimator)
- tests/rand.py L59
- feature_correlation.py L139
- ~manifold.py L332~ (this is on the transformer)
- influence.py L113
- classifier/base.py L132
- rocauc.py L212 and 214
- validation_curve.py L181
- importances.py L144
- learning_curve.py L200
- ~elbow.py L311~ (this is on the estimator)
- threshold.py L213
- prcurve.py L242 


Because of this, I believe the fix will have to be an override of `Visualizer.get_params` and `Visualizer.set_params` in order to ensure that our `getattr` wrapper is used correctly.

**Comment by phbillet** [comment]
[yellowbrick.zip](https://github.com/DistrictDataLabs/yellowbrick/files/5911636/yellowbrick.zip)
Hi,
I really like your visualization software, this problem with sklean 0.24 was annoying, so I have realized the proposed corrections and launched the tests, it does not seem bad. The modified files contain comments with my trigram pbi (a legacy from mainframe age).
Unfortunately at the moment I do not know how to use github correctly, so you will find my corrections in the zip file in attachment.
I hope it will interest somebody.

Have nice day

**Comment by bbengfort** [comment]
Hi @phbillet thank you so much for using Yellowbrick and working to fix the code; we really appreciate you're attempting to tackle this problem. I totally understand that you're not familiar with GitHub, and I appreciate you trying to find a solution to sending us some code. Unfortunately, an unsigned zip file represents a bit of a security threat since we can't scan what's inside of it before we download and extract it. As a matter of policy, I've had to remove your comment with the attachment. 

If you're not familiar with the fork and pull request policy, perhaps you could upload your code base to your own repository and send us a link to that? We'd be happy to review your code there -- or if you're more familiar with BitBucket, GitLab, etc. we'd be happy to take a look at the repository host of your choice.

**Comment by phbillet** [comment]
I have made the corrections proposed by @bbengfort : https://github.com/phbillet/yellowbrick
After launching the tests, I have this result:
30 failed, 951 passed, 213 skipped, 21 xfailed, 40 xpassed, 24 warnings in 709.65s (0:11:49)

**Comment by bbengfort** [comment]
@phbillet Thank you so much! I've opened the PR for you since you're not familiar with GitHub; we can move our comments and discussion over there: https://github.com/DistrictDataLabs/yellowbrick/pull/1146
